### DISCUSSION TITLE
Fuzzing - Required but nullable

### DISCUSSION THREAD

**Discussion by thim81** [apideck-libraries/portman#264] [Q&A]
Currently Portman, fuzzes “required” properties by removing them and expecting a 4xx response
But what if in OpenAPI the property is “required” but allowed to be “nullable”, what should Portman do?

Example:
```yaml
components:
  schemas:
    Pet:
      type: object
      required:
        - url
      properties:
        name:
          type: string
          nullable: true
          example: 'doggie'
        url:
          type: string
          nullable: true
          example: 'https://www.example.net'
```

What would be the expected fuzzing behaviour?

Options:

1. Remove the URL property and expect a 4xx response?
2. Remove the URL property and expect a 2xx response?
3. Keep the property but with null value and expect a 4xx response?
4. Skip the variation, since we are testing for 4xx variations, which is not applicable for a null value, since that would return a 200
