### DISCUSSION TITLE
Use of "excludeForOperations"

### DISCUSSION THREAD

**Discussion by MarcoFierimonte** [apideck-libraries/portman#290] [Q&A]
Hi all :) 

I am trying to use excludeForOperations flag in the contractTests section, in this way:

```yaml
"tests": {
    "contractTests": [
      {
        "openApiOperation": "*::*/*",
        "excludeForOperations": ["POST::*/*"],
        "schemaValidation": {
          "enabled": true
        }
      },
      {
        "openApiOperation": "POST::*/*",
        "statusCode": {
          "enabled": true,
          "code": 201
        }
      },
      {
        "openApiOperation": "GET::*/*",
        "statusCode": {
          "enabled": true,
          "code": 200
        }
      },
      {
        "openApiOperation": "DELETE::*/*",
        "statusCode": {
          "enabled": true,
          "code": 204
        }
      },
      {
        "openApiOperation": "PATCH::*/*",
        "statusCode": {
          "enabled": true,
          "code": 204
        }
      },
      {
        "openApiOperation": "*::*/*",
        "excludeForOperations": ["POST::*/*"],
        "responseTime": {
          "enabled": true,
          "maxMs": 2500
        }
      }
    ]
  }
```
so if I understood well I expected, for example, that all the POST api are generated without TEST for the "responseTime" and "schemaValidation" types, is it correct?
The generated postman collection instead have the tests also for the POST api, am I writing wrong the file?

Thanks a lot.
Marco F.
