### DISCUSSION TITLE
How to change Auth type

### DISCUSSION THREAD

**Discussion by sumitriotinto** [apideck-libraries/portman#358] [Q&A]
Hey Team , 

Trying to change the auth type from bearer token to apikey using below config

```json
{
  "version": 1.0,
  "globals": {
    "securityOverwrites": {
      "apiKey": {
		"key": "Authorization",			
        "value": "{{apiKey}}",
		"in": "header"
      }
    }
  }
}
```
    
schema.yml :
```yaml
securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
      bearerFormat: Token
````

but still auth type remains bearer token could you hep me with any example.
