### DISCUSSION TITLE
Does overwriteRequestHeaders work for the Authorization header

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#580] [Q&A] [answered]
Hi.   This is my first question, so I'd be remiss if I didn't start by saying how awesome Portman is.   This is such a wonderful tool. My sincere thanks to the authors and the community!

I've got a variance test which includes the following:
```yaml
        - name: noAuthHeader
          overwrites:
            - overwriteRequestHeaders:
                - key: Authorization
                  remove: true
```

But in the generated collection, I still see the default Authorization header with its value in the Postman GUI.
<img width="717" alt="Screenshot 2024-06-14 at 5 56 32 PM" src="https://github.com/apideck-libraries/portman/assets/4774656/93541741-2173-40ce-934f-7abee7a0c9f2">

Am I misunderstanding how overwriteRequestHeaders should work?

**Comment by thim81** [comment]
hi @jpjpjp 

Would be able to share your OpenAPI and Portman config, so that we can try to reproduce the behaviour?

**Comment by jpjpjp** [comment]
With pleasure, @thim81. Attached are simplified versions of both, which I was able to use to reproduce the issue.

[yaml-configs.zip](https://github.com/user-attachments/files/15847667/yaml-configs.zip)

**Comment by thim81** [comment]
We got a [PR](https://github.com/apideck-libraries/portman/pull/582) in the making that should handle the special "Authorization" header better. 

Long story short: within Postman the "Authorization" header is generated based on the Postman authentication option (if they are used).

So we will add the behaviour that handles the removal based on:
- overwriteRequestHeaders
- overwriteRequestSecurity
- overwriteCollectionSecurityValues

In your case:

```
overwrites:
            - overwriteRequestHeaders:
                - key: Authorization
                  remove: true
```

Will set the Postman Authentication option to "noauth", which will unset the header.

**Before:**
<img width="1077" alt="image" src="https://github.com/apideck-libraries/portman/assets/952446/90ede374-8bbe-4df5-8b92-e3d8df4128d1">

<img width="1081" alt="image" src="https://github.com/apideck-libraries/portman/assets/952446/63d7242d-73a6-46d6-83fe-71ff41f70600">

**After:**
<img width="595" alt="image" src="https://github.com/apideck-libraries/portman/assets/952446/66617cad-f81a-4ece-9898-57d5cc692f3e">
<img width="1079" alt="image" src="https://github.com/apideck-libraries/portman/assets/952446/4b9bffdd-6772-4af5-8595-4d09fbc7609f">

We are in the process of adding the necessary test and using your provided config to validate the improvements.

**Comment by thim81** [comment]
@jpjpjp This is the result of using your provided config with the changes from the PR:
<img width="1073" alt="image" src="https://github.com/apideck-libraries/portman/assets/952446/f4427d36-cb7b-4205-aa15-09cf88da7350">

<img width="721" alt="image" src="https://github.com/apideck-libraries/portman/assets/952446/0f31b2e4-4014-429f-a628-9f36cc0086cb">

I think that this is the expected result?

I'll do some more validation and than it will be ready to be included in the next release.

**Reply by jpjpjp** [reply]
Hi @thim81, yes this is the expected result!

I was going to mark this as the answer, but perhaps it would make sense for you to respond when the new version is ready?

**Reply by thim81** [reply, marked as answer]
Hi @jpjpjp,

We just released Portman v1.27.0, which includes all your README suggestions and improvements for handling the "Authorization" overwrite properly.

Thanks for your clear feedback, which helped us reproduce the behavior and improve the logic in Portman.

We always appreciate feedback and suggestions, so don't hesitate to share them.

**Reply by jpjpjp** [reply]
Thank you @thim81!  Confirmed that when using Portman v1.2.7.0 that:

```yaml
            - overwriteRequestHeaders:
                - key: Authorization
                  remove: true
```
Completely removes the Authorization header from the generated postman request.

Thank you!
