### DISCUSSION TITLE
Complex logic in assignVariables and overwrites

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#588] [Q&A] [answered]
I'm learning how to use `assignVariables` and `overwrites` to use the responses from previous requests as input to subsequent requests.   My Portman configuration contains the following logic:

```yaml
# Set a general rule to assign a postman <tab>id variable from the response bodies
# of any POST or GET requests
assignVariables:
  - openApiOperation: POST::*
    collectionVariables:
      - responseBodyProp: id
        name: <tag>Id
  - openApiOperation: GET::*
    excludeForOperations:
      - "GET::/*/{id}"
    collectionVariables:
      - responseBodyProp: <tag>[0].id
        name: <tag>Id
# Set a general rule to use the most recently assigned id variable from the 
# previous POST or GET request as the id to use in any requests that take an id
overwrites:
  - openApiOperation: "*::/*/{id}"
    overwriteRequestPathVariables:
      - key: id
        value: '{{<tag>Id}}'
        overwrite: true
```

Is it possible to do any customized logic when assigning variables?   For example, I might want to check if a  Postman environment variable `isMockServer` is false before assigning the request path id variable to the <tag>Id based on the response of the previous request. 

As another example, I might want to walk a list of objects in a responseBody and examine each object's `color` attribute before setting variables like `redMarbleId` or `blueMarbleId` that might be used in subsequent tests.

I think it would be possible to do something like this using the `extendTests` attribute in a variation test, but I was wondering if this logic could be applied at the global level.
