### DISCUSSION TITLE
Can you set a requestBody attribute to an integer using a postman variable?

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#589] [Q&A] [answered]
Thanks to Portman's great documentation and helpful answers in this forum, I've been writing variation tests that use Postmam environment variables in request bodies.   However I'm having trouble setting these attributes to integers when that is the required type.

TL;DR

When I use this syntax:
```yaml
          overwrites:
            - overwriteRequestBody:
                - key: intAttribute
                  value: "{{numericPostmanVariable}}"
                  overwrite: true
```

The resulting generated request body looks like this:
```json
{
  "intAttribute": "{{numericPostmanVariable}}"
}
```
This fails validation since my spec says that intAttribute is an integer. However, if I manually remove the quote marks around the variable, it works as desired.

If I try to remove the quotes in the overwrite directive:
```yaml
          overwrites:
            - overwriteRequestBody:
                - key: intAttribute
                  value: {{numericPostmanVariable}}
                  overwrite: true
```

The resulting generated request body looks like this:
```json
{
  "intAttribute": {}
}
```
Is it possible to assign a request body attribute to a Postman variable without having it enclosed in quotes?  I've played around with a few escape sequences but haven't gotten anything to work yet.

Here is a more complete example of my configuration and the result requests in Postman, if that is helpful

```yaml
version: 1.0
tests:
  variationTests:
    - openApiOperationId: createCategory
      openApiResponse: '400'
      variations:
        - name: groupIdIsNotGroup
          overwrites:
            - overwriteRequestBody:
                - key: is_group
                  value: false
                  overwrite: true
                - key: group_id
                  value: {{_categoryId}}  # _categoryId is a Postman variable set to an integer in a previous test
                  overwrite: true
          tests:
            contentTests:
              - responseBodyTests:
                  - key: message
                    value: Invalid Request Body
                  - key: errors
                    minLength: 1
                  - key: errors[0].errMsg
                    value: Requested 'group_id':${requestBody.group_id} is not an existing category group
        - name: categoryGroupAsChild
          overwrites:
            - overwriteRequestBody:
                - key: is_group
                  value: true
                  overwrite: true
                - key: children
                  value: ["{{_categoryGroupId}}"] # _categoryGroupId is a Postman variable set to an integer in a previous test
                  overwrite: true
          tests:
            contentTests:
              - responseBodyTests:
                  - key: message
                    value: Invalid Request Body
                  - key: errors
                    minLength: 1
                  - key: errors[0].errMsg
                    value: Specified child category id:'${id}' is a category group
```

Here is the first request in the Postman collection
<img width="851" alt="No Quotes" src="https://github.com/apideck-libraries/portman/assets/4774656/8c0c9a15-0ecd-4861-ab72-f620712401c5">

Here is the section request in the Postman collection:
<img width="870" alt="QuotesInBody" src="https://github.com/apideck-libraries/portman/assets/4774656/d122ede1-3903-4e6e-92b8-326b86fb2a93">

**Comment by thim81** [comment]
hi @jpjpjp 

According to the tests

```
{
        key: 'name',
        value: '{{$randomInt}}',
        overwrite: true
      }
```
https://github.com/apideck-libraries/portman/blob/8a9373a295b44e6249156a170b603b842558a5d9/src/application/overwrites/overwriteRequestBody.test.ts#L275

Resulting in:

```
exports[`overwriteRequestBody should overwrite the body param with raw {{$randomInt}} instead of string 1`] = `
"{
    \\"name\\": {{$randomInt}},
    \\"owner_id\\": \\"12345\\",
    \\"image_url\\": \\"https://www.spacex.com/static/images/share.jpg\\",

```

Let me do some more tests, with a regular variable and your examples .

**Comment by jpjpjp** [comment]
Thank you, @thim81! Just to be clear, I haven't been using the syntax of including '$' inside the braces but before my variable name. 
I did try this once I saw your post, but it simply adds that $ into the result and doesn't seem to affect how the request body is when the overwrites directive includes quotes or not.

I also tried your syntax of using single quotes instead of double quotes, but that also seems to have the same outcome.

**Comment by thim81** [comment]
The `$` are used for Dynamic Postman variables: https://learning.postman.com/docs/tests-and-scripts/write-scripts/variables-list/

regular variables are just `{{varName}}`.

I still have to find time to do the tests, to verify if the regular number variables are properly parsed.

**Comment by thim81** [comment, marked as answer]
hi @jpjpjp 

Can you try the following? 
Make the numeric variable a string `{{{varName}}}`. Use your variable name, surrounded by `{{{` at the start and `}}}`at the end, with quotes around it. That will trigger Portman to convert it into a numeric variable (and not as a default string).

```
 overwriteRequestBody:
                - key: is_group
                  value: false
                  overwrite: true
                - key: group_id
                  value: '{{{_categoryId}}}' # _categoryId is a Postman variable set to an integer in a previous test
                  overwrite: true
```

This should result in numeric (non-string) variable overwrite.

If you find a clear way to describe this in the [readme](https://github.com/apideck-libraries/portman?tab=readme-ov-file#:~:text=.%20as%20key.-,value,-(Any)%20%3A%20The), feel free to make a suggestion 🤝 .

**Reply by jpjpjp** [reply]
Hi. @thim81 

Good news:   Using the single quote/3 curly braces syntax in my yaml configuration is working!

Specifically, this configuration:
```yaml
            - overwriteRequestBody:
                - key: is_group
                  value: false
                  overwrite: true
                - key: group_id
                  value: '{{{_categoryId}}}' # _categoryId is an Postman variable set to an integer in a previous test
                  overwrite: true

```

Is indeed generating a request body with the `group_id` attribute set to the Postman variable without quotes around it.

Bad news: Using the single quote/3 curly braces syntax within an array (square braces) isn't working.

This syntax:
```yaml
            - overwriteRequestBody:
                - key: is_group
                  value: true
                  overwrite: true
                - key: children
                  value: ['{{{_categoryGroupId}}}']
                  overwrite: true

```

Generates this error when I run Portman:

```
undefined:9
        {{_categoryGroupId}}}"
         ^

SyntaxError: Expected property name or '}' in JSON at position 237 (line 9 column 10)
    at JSON.parse (<anonymous>)
    at overwriteRequestBodyJson (XXX..XXX/api-server-demo/node_modules/@apideck/portman/dist/application/overwrites/overwriteRequestBody.js:35:25)
```

If I'm reading the error correctly, it appears that Portman is converting the YAML configuration to JSON, and the generated JSON is somehow invalid.  I wasn't able to find a JSON version of my configuration in Portman's tmp directory, so I tried running the attached, simplified YAML configuration through an [online YAML to JSON converter](https://jsonformatter.org/yaml-to-json)and then ran Portman with the generated JSON configuration. The json looks valid to me, but it does generate the same error

Both of the simplified YAML and generated JSON are in the attached [yaml-configs.zip](https://github.com/user-attachments/files/15913904/yaml-configs.zip)

If you have any suggestions I'd appreciate it (and I'll surely think about how to update the docs).

**Reply by thim81** [reply]
hi @jpjpjp 

I'm afraid that the numeric variable handling inside an array is not supported at this stage.

You could try the following workarounds to see if they could unblock you:
REMARK: These are untested but might work.

```
            - overwriteRequestBody:
                - key: is_group
                  value: true
                  overwrite: true
                - key: children.[]
                  value: '{{{_categoryGroupId}}}'
                  overwrite: true

```

Or first, remove the array and then add your one item:

```
            - overwriteRequestBody:
                - key: is_group
                  value: true
                  overwrite: true
                - key: children
                  remove: true
                - key: children.[0]
                  value: '{{{_categoryGroupId}}}'
                  overwrite: true
```

**Reply by jpjpjp** [reply]
Hi @thim81 For the first suggestion, I ended up with this (malformed syntax) in my request body:

```json
    "children": {
        "": {
            "": {{_categoryGroupId}}
        }
    }
```

I got the same "undefined:9 {{_categoryGroupId}}}" error as I had above for the second suggestion.

I managed to work around this by changing how I set the postman variable.   I'm including the details below in case another Portman user is interested, but I just changed the variable to a stringified list.

I'll mark your previous answer as correct and give some thought on how to modify the docs.

Thank you!
-------------------------------
Details on the workaround:
I updated the request that sets these postman variables to include another one as follows:
```js
pm.test("Set _listOfCategoryGroupIds to all the ids of category groups", function () {
    let listOfCategoryGroupIds = []
    pm.response.json().categories.forEach(function(category) {
        if (category.is_group === true) {
            pm.expect(category.id).to.be.a('number');
            listOfCategoryGroupIds.push(category.id)
        }
    });
    pm.collectionVariables.set("_listOfCategoryGroupIds", JSON.stringify(listOfCategoryGroupIds));
    pm.collectionVariables.set('_numCategoryGroups', listOfCategoryGroupIds.length);
});
```

After validating that it created the a variable with a stringified list of integers in it, I stringified the function and updated my configuration as follows:

```yaml
tests:
  variations:
    - openApiOperationId: getAllCategories
      # Start with a valid request so we can set variables used by other tests
      openApiResponse: '200'
      variations:
        - name: getExistingCategoryInfo
          tests:
            extendTests:
              # These tests will find examples of existing data types in the
              # response and set Postman variables based on their attributes
              # to be used in subsequent requests
              # TODO - When not using a mock server ensure that these types
              # are created prior to this variation test!
            - tests:
              - "pm.test(\"Set _listOfCategoryGroupIds to all the ids of category groups\", function () {\n    let listOfCategoryGroupIds = []\n    pm.response.json().categories.forEach(function(category) {\n        if (category.is_group === true) {\n            pm.expect(category.id).to.be.a('number');\n            listOfCategoryGroupIds.push(category.id)\n        }\n    });\n    pm.collectionVariables.set(\"_listOfCategoryGroupIds\", JSON.stringify(listOfCategoryGroupIds));\n    pm.collectionVariables.set('_numCategoryGroups', listOfCategoryGroupIds.length);\n});\n"
        - name: categoryGroupAsChild
          overwrites:
            - overwriteRequestBody:
                - key: is_group
                  value: true
                  overwrite: true
                - key: children
                  value: '{{{_listOfCategoryGroupIds}}}'
                  overwrite: true
          tests:
            contentTests:
              - responseBodyTests:
                  - key: message
                    value: Invalid Request Body
                  - key: errors
                    minLength: 1
                  - key: errors[0].errMsg
                    contains: Specified child category id
                  - key: errors[0].errMsg
                    contans: is a category group

```
