### DISCUSSION TITLE
Use backtick instead of double quotes for key/value contentTests to support Template Literal variable expansion

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#590] [Ideas]
It would be handy if contentTests like this one:

```yaml
            contentTests:
              - responseBodyTests:
                  - key: message
                    value: Invalid Request Body
                  - key: errors
                    minLength: 1
                  - key: errors[0].errMsg
                    value: "Requested 'group_id':${JSON.parse(pm.request.body.raw).group_id} is not an existing category group"
```

Generated a pm.test that used the backtick syntax to represent the string in the test instead of double quotes as it does now

For example in the below I simply replaced the quote marks with back ticks:
```js
// Response body should have value "Requested 'group_id':${JSON.parse(pm.request.body.raw).group_id} is not an existing category group" for "errors[0].errMsg"
if (_resErrors0ErrMsg !== undefined) {
pm.test("[POST]::/categories - Content check if value for 'errors[0].errMsg' matches 'Requested 'group_id':${JSON.parse(pm.request.body.raw).group_id} is not an existing category group'", function() {
  pm.expect(_resErrors0ErrMsg).to.eql(`Requested 'group_id':${JSON.parse(pm.request.body.raw).group_id} is not an existing category group`);
})};
```

And this test passes.

I can't think of any reason why using backticks as the default all the time would cause problems, but I readily admit I may not be thinking through all the use cases!   

An alternate approach might be to support a new keyword, ie: using `templateLiteral`, instead of `value` could use the backticks.

**Comment by thim81** [comment]
It looks like you are experiencing the limits of the Postman syntax. 
I'm not sure if you can evaluate the `${JSON.parse(pm.request.body.raw).group_id}` within a test?

My suggestion would be to use contentTests with the "[contains](https://github.com/apideck-libraries/portman/tree/main#:~:text=contains%20(String)%20%3A%20The%20value%20that%20will%20be%20used%20to%20check%20if%20the%20value%20is%20present%20in%20the%20value%20of%20the%20response%20body%20property.)" check.

You want to validate the error message, not the exact response.

```
            contentTests:
              - responseBodyTests:
                  - key: message
                    value: Invalid Request Body
                  - key: errors
                    minLength: 1
                  - key: errors[0].errMsg
                    contains: is not an existing category group
```

The content check result will be the same, since it will tell you that error message is returned as expected, but this will make the test more generic and less complicated.

**Reply by jpjpjp** [reply]
Hi @thim81.   I can tell you that the example test I provided, which evaluates `${JSON.parse(pm.request.body.raw).group_id}` within a Template Literal, does indeed work.

With that said, your simple solution to use the `contains` check is certainly an acceptable test without complicating Portman anymore.   

As I think about it more, it occurs to me that the utility of using template literals in automated tests is limited to variables that already exist. For example, I don't think you could write a test that looks for a string that contains a Postman environment variable since you need to first turn that into a Javascript variable via a call to `pm.collectionVariables.set(...)`, so a simple `key`/`value` automated test would not be sufficient.

Thanks as always.

**Reply by thim81** [reply]
hi @jpjpjp 

Not sure what your use-case here, can you provide an simple example what you want todo and what you expect?

You could use a variable as a content check value, like:

```
  contentTests:
    - openApiOperation: "*::/*/{id}"
      responseBodyTests:
        - key: rank
          value: '{{rank}}'
```

Which will lead to this:
<img width="984" alt="image" src="https://github.com/apideck-libraries/portman/assets/952446/a02141cb-2a8b-457e-8221-9c8de343a54e">

Portman has logic build in to detect a variable and apply a conversion, depending on the case (overwrite, assign, contentTests, ...) . In this case the variable value will be used in the content check.
