### DISCUSSION TITLE
Use of Template Expressions with collectionVariables

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#595] [Q&A] [answered]
Hi,

  I had a question about the syntax for Template Expression expansion when operating with a `collectionVariables` block.   I have the following configuration:
  
```yaml
# Set a general rule to assign a postman id variable from the response bodies
# of any POST or GET requests
assignVariables:
  - openApiOperation: POST::*
    collectionVariables:
      - responseBodyProp: id
        name: <tag>Id
      - value: <tag>
        name: currentTag
```

When I look at the generated test I see the following:

```js
// pm.collectionVariables - Set categoriesId as variable for jsonData.id
if (_resId !== undefined) {
   pm.collectionVariables.set("categoriesId", jsonData.id);
   console.log("- use {{categoriesId}} as collection variable for value",jsonData.id);
} else {
   console.log('INFO - Unable to assign variable {{categoriesId}}, as jsonData.id is undefined.');
};

// pm.collectionVariables - Set fixed value for currentTag variable 
pm.collectionVariables.set("currentTag", "<tag>");
console.log("- use {{currentTag}} as collection variable for value", "<tag>");
```

So it seems that when I use  `<tag>` as the value in the for the `name` key after specifying `responseBodyProp`, it gets expanded in the generated test, but when I use it as the value for the `value` key it doesn't expand.

Is this just my poor usage or something that isn't supported.
