### DISCUSSION TITLE
overwriteRequestQueryParams with value of zero?

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#603] [Q&A] [answered]
Is it possible to use the `overwriteRequestQueryParams` to set a query param value to zero?

I've got a configuration that looks like this:
```yaml
tests:
  integrationTests:
    - name: /transactions tests
      operations:
        - openApiOperationId: getAllTransactions
          openApiResponse: "200"
          variations:
            - name: NoManualAccountsFilterWorks
              overwrites:
                - overwriteRequestQueryParams:
                    - key: manual_account_id
                      value: 0
              tests:
                contentTests:
                  - responseBodyTests:
                      - key: transactions
                        length: "{{_numNonManualAccountTrans}}"
```

However, I'm finding that the portman generated request looks like this:

http://localhost:3000/v2/transactions?manual_account_id=

Where the 0 value is interpreted as nothing.

Is it possible to set a query param to zero?  Perhaps there is a different directive?
