### DISCUSSION TITLE
Merge several definitions

### DISCUSSION THREAD

**Discussion by vampyar** [apideck-libraries/portman#635] [Q&A] [answered]
How I can using separate file and merge in the one file for overwrites field ?

```yaml
overwrites:
    - $ref: './tests/portman/definitions/overwrites-vehicle.yml#/overwrites'
    - $ref: './tests/portman/definitions/overwrites-vehicle-v2.yml#/overwrites'
```
in the case I got error 

```bash
 Invalid Portman Config:                ./tests/portman/portman-config.crm.yml
[
  {
    message: "'0' property type must be object",
    path: '{base}.overwrites.0',
    context: { errorType: 'type' }
  },
  {
    message: "'1' property type must be object",
    path: '{base}.overwrites.1',
    context: { errorType: 'type' }
  }
]
```

I need split this entity on the two file or more, and after combine to one in the overwrite or 
```yaml
tests:
  contentTests:
     - $ref : ...
     - $ref : ... 
```

**Comment by thim81** [comment]
hi @vampyar 

We created a small example using $references: https://github.com/apideck-libraries/portman/tree/main/examples/config-references, which could be helpful.

**Comment by vampyar** [comment]
hi @thim81 Yep I got it but your example you include one `ref` how I can did it like multiple time  
```
version: 1
tests:
  contractTests:
    $ref: './examples/config-references/definitions/test-contracts.yaml#/contractTests'
  contentTests:
    $ref: './examples/config-references/definitions/test-content.yaml#/contentTests'
globals:
    $ref: 'https://raw.githubusercontent.com/apideck-libraries/portman/main/examples/config-references/definitions/globals.yaml#/globals'
```
like example:
```
version: 1
tests:
  contractTests:
    $ref: './examples/config-references/definitions/test-contracts.yaml#/contractTests'
    $ref: './examples/config-references/definitions/test-contracts1.yaml#/contractTests'
  contentTests:
    $ref: './examples/config-references/definitions/test-content.yaml#/contentTests'
globals:
    $ref: 'https://raw.githubusercontent.com/apideck-libraries/portman/main/examples/config-references/definitions/globals.yaml#/globals'
```
