### DISCUSSION TITLE
How does portman handle form encoded array query params?

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#640] [Q&A] [answered]
I have an endpoint that supports a form encoded query param `ids`.   

This is the spec definition:

```yaml
paths:
  /categories
    get:
      parameters:
        - name: ids
          in: query
          description: A form serialized array of category IDs to filter the
            results. <br>
            IDs that do not exist are ignored.
          required: false
          schema:
            type: array
            items:
              type: integer
          style: form
          examples:
            child_ids:
              value:
                - 315162
                - 315163
                - 315164
            top level:
              value:
                - 83
                - 84
```

In my first attempt to write a test that used this category I just tried setting a single `ids` parameter:

```yaml
operations:
    - openApiOperationId: getAllCategories
      openApiResponse: '200'
      variations:
        - name: OneIdsParameter
          operationPreRequestScripts:
            - scripts:
              - file:./specs/v2/tests/scripts/categories/pre-skipGetCategoryGroupIfNone.js
          overwrites:
            - overwriteRequestQueryParams:
                - key: ids
                  value: "{{_categoryGroupId}}"
```

I was surprised that regardless of the type of variable I passed into the "value" field, that when the generated, the test looked like this in postman:

GET {{baseUrl}}/categories?ids={{_categoryGroupId}}&ids={{_categoryGroupId}}&ids={{_categoryGroupId}}

So, the same variable is passed three times as the form encoded parameter.

In my ideal world, the behavior would be as follows:

1)  If the variable is a single entity (ie: string or integer), the result is simply:
GET {{baseUrl}}/categories?ids={{_categoryGroupId}

2) If the variable, let's call it idList, looks like a list, the result is 
GET {{baseUrl}}/categories?ids={{idList[0}}&ids={{idList[1]}}&ids={{idList[2]}}

However, I realize that portman may not know the current value of the Postman variable when generating the test.   In this case, I think its reasonable that the test writer create a pre-request script to evaluate the variable and create new individual list entry variables, ie:

Prerequest script:
```js
// Skip the test if a category group was not found
if (!pm.collectionVariables.get("_listOfAllCategoryIds")) {
    // If _categoryGroupId is not set, skip to the next request
    console.log(`Skipping ${pm.info.requestName} since no list of categories was available`)
    pm.execution.skipRequest();
} else {
   // Define variables for the first 3 elements of the list if it is a list
    _listOfAllCategoryIds = json.Parse(pm.collectionVariables.get("_listOfAllCategoryIds"))
    pm.collectionVariables.set("_categoryId1", _listOfAllCategoryIds[0] || 0);
    pm.collectionVariables.set("_categoryId2", _listOfAllCategoryIds[1] || 0);
    pm.collectionVariables.set("_categoryId3", _listOfAllCategoryIds[2] || 0);
}
```

and then write a test that looks more like this:

```yaml
operations:
    - openApiOperationId: getAllCategories
      openApiResponse: '200'
      variations:
        - name: OneIdsParameter
          operationPreRequestScripts:
            - scripts:
              - file:./specs/v2/tests/scripts/categories/pre-skipGetCategoryGroupIfNone.js
          overwrites:
            - overwriteRequestQueryParams:
                - key: ids
                  value: "{{_categoryId1}}"
                - key: ids
                  value: "{{_categoryId2}}"
                - key: ids
                  value: "{{_categoryId3}}"
```

However, the request generated from this test definition looks like this:

GET {{baseUrl}}/categories?ids={{_categoryId3}}&ids={{_categoryId3}}&ids={{_categoryId3}}

So it seems like portman is generating the same 3 values for any value that is listed as a form encoded array (at least given my spec which does include 3 ids in the first example!)

Is this a corner case, not well handled yet by Portman?

**Comment by thim81** [comment]
hi @jpjpjp 

It is a corner case, which we did not ran into before.
We will try to extend query param logic to support multiple query params with the same name.

**Comment by thim81** [comment]
hi @jpjpjp 

We are working on [solution](https://github.com/apideck-libraries/portman/pull/643), which should result in the handling of form encoded array query params.

This is the result 
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/2c2629b4-f2ed-4298-93ac-639bb323c387">

See the [PR](https://github.com/apideck-libraries/portman/pull/643) for more details.

**Comment by thim81** [comment]
hi @jpjpjp 

We just release [Portman v1.30](https://github.com/apideck-libraries/portman/releases/tag/v1.30.0), which allows you to overwrite of form encoded array query params.

Thanks for sharing this edge case.

**Comment by jpjpjp** [comment]
Hi @thim81,

  I'm afraid there is an extra corner in my corner case that is still causing an issue. A form-encoded query param can be of variable length, so a user should be able to make requests with 0, 1, 2, etc. instances of the query param. Portman v1.30 handles test cases where the number of form-encoded query params set matches the number of query params set in the first example in the spec (3 in my case) but fails if there is a different number.
  
  Here is an example set of tests that will throw an error:
```yaml
operations:
    - openApiOperationId: getAllCategories
      openApiResponse: '200'
      variations:
        - name: TwoGoodOneBadIdsParameter
          operationPreRequestScripts:
            - scripts:
              - file:./specs/v2/tests/scripts/categories/pre-generateExistingCatetoryIds.js
          overwrites:
            - overwriteRequestQueryParams:
                - key: ids
                  value: "{{_categoryId1}}"
                - key: ids
                  value: "{{_categoryId2}}"
                - key: ids
                  value: "{{_nonExistingCategoryId}}"
          tests:
            $ref: ../contracts/variation-contract-tests.yaml 
            contentTests:
              - responseBodyTests:
                  - key: categories
                    maxLength: 2
                  - key: categories[0].id
                    value: "{{_categoryId1}}"
                  - key: categories[1].id
                    value: "{{_categoryId2}}"
    - openApiOperationId: getAllCategories
      openApiResponse: '404'
      variations:
        - name: AllBadIdsParameter
          operationPreRequestScripts:
            - scripts:
              - file:./specs/v2/tests/scripts/categories/pre-generateExistingCatetoryIds.js
          overwrites:
            - overwriteRequestQueryParams:
                - key: ids
                  value: "{{_nonExistingCategoryId}}"
                - key: ids
                  value: "{{_nonExistingCategoryId2}}"
          tests:
            $ref: ../contracts/variation-contract-tests.yaml 
            contentTests:
              - responseBodyTests:
                  - key: message
                    value: Not Found
                  - key: errors
                    minLength: 2
                  - key: errors[0].errMsg
                    contains: here is no category with the id
```

Notice that the first request sets three instances of the `ids` param, but the second instance only sets two.   This causes the following runtime error when generating the tests:

```bash
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'value')
    at <anonymous> (../portman/dist/application/overwrites/overwriteRequestQueryParams.js:61:38)
```

I had hoped to try fixing this myself and perhaps submit a PR, but I think the problem may extend beyond just the code in overwriteRequestQueryParams.js.

The issue appears to be that the heart of the overwriteRequestQueryParams function is a loop that iterates with:

```ts
pmOperation.item.request.url.query.each(pmQueryParam => {
}
```
But from what I could tell when iterating through my requests in the debugger, the query object was the same for all the requests: one instance of the optional `format` parameter and three instances of the optional `ids` parameter.   This means that tests that try to set more than 3 instances of the query param will only set the first three, and of course, tests that try to set one or two instances will generate that runtime error.

I was reluctant to mess with the code that sets up the pmOperation object, so I thought I'd report my findings here.  I realize that this is a very unique corner case so if you aren't able to support it, that is completely reasonable!   I can adjust my tests with an understanding of the limitations.
