### DISCUSSION TITLE
Does oneOf in responseBodyTests support environment variables?

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#650] [Q&A] [answered]
I'm wondering if it's possible to create a content test to see if a field in a response body matches one of a few postman environment variables.

I've tried the following:
```yaml
          tests:
            contentTests:
              - responseBodyTests:
                  - key: children
                    minLength: 2
                  - key: childrend[0].id
                    oneOf: ["{{{_testCreatedCategoryId}}}", "{{{_testCreatedCategoryId2}}}"]
                  - key: childrend[1].id
                    oneOf: 
                      - "{{_testCreatedCategoryId}}"
                      - "{{_testCreatedCategoryId2}}"
```
Both syntaxes are accepted by portman, but neither generates a valid test.  Here is what the above generates:

```js
// Response body should have "childrend[0].id"
pm.test("[PUT]::/categories/:id - Content check if 'childrend[0].id' exists", function() {
   pm.expect(_resChildrend0Id !== undefined).to.be.true;
});

// Response body should be one of the values "{{{_testCreatedCategoryId}}},{{{_testCreatedCategoryId2}}}" for "childrend[0].id"
if (_resChildrend0Id !== undefined) {
pm.test("[PUT]::/categories/:id - Content check if value for 'childrend[0].id' is matching one of: '{{{_testCreatedCategoryId}}},{{{_testCreatedCategoryId2}}}'", function() {
  pm.expect(jsonData.childrend[0].id).to.be.oneOf(["pm.collectionVariables.get("{_testCreatedCategoryId}")","pm.collectionVariables.get("{_testCreatedCategoryId2}")"]);
})};

// Set property value as variable
const _resChildrend1Id = jsonData?.childrend?.[1]?.id;

// Response body should have "childrend[1].id"
pm.test("[PUT]::/categories/:id - Content check if 'childrend[1].id' exists", function() {
   pm.expect(_resChildrend1Id !== undefined).to.be.true;
});

// Response body should be one of the values "{{_testCreatedCategoryId}},{{_testCreatedCategoryId2}}" for "childrend[1].id"
if (_resChildrend1Id !== undefined) {
pm.test("[PUT]::/categories/:id - Content check if value for 'childrend[1].id' is matching one of: '{{_testCreatedCategoryId}},{{_testCreatedCategoryId2}}'", function() {
  pm.expect(jsonData.childrend[1].id).to.be.oneOf(["pm.collectionVariables.get("_testCreatedCategoryId")","pm.collectionVariables.get("_testCreatedCategoryId2")"]);
})};

```

If this isn't supported, that is fine.  Please don't treat this as a must-have feature request or bug report.   I was just wondering if there was a different syntax that might work.

**Comment by thim81** [comment]
hi @jpjpjp,

Let me run some tests, how portman handles it. At first glance, I suspect an unneeded string conversion using backticks.

**Reply by thim81** [reply]
hi @jpjpjp 

Found the specific case and created a [PR](https://github.com/apideck-libraries/portman/pull/651) for it.

Result:
<img width="1348" alt="image" src="https://github.com/user-attachments/assets/b02c3e89-6f01-4d79-bfcd-e3a0b233c059">

**Reply by thim81** [reply]
can you help me again, remind me what the triple {{{ }}} behaviour was?

NVM: it is for using templated variables.

Not sure if that would be a valid case?

**Reply by jpjpjp** [reply]
Yes, the triple brace tells portman not to treat the value as a string (ie: put quotes around it).

But upon reflection, I think I've found this to be unnecessary in responseBody tests. Since Postman treats all collection variables as strings, it seems to have some smarts in the pm.expect logic so that it works OK comparing numbers with numbers stored in collection variables (as strings). 

I think that the only place that the triple braces are needed is requestBodyOverrides.

Hope this helps!

**Reply by thim81** [reply]
Thanks 🙏 for the explanation. 
Based on this, the PR is ready and the fix will be included in the next release.

**Reply by jpjpjp** [reply]
Thanks!   I ran the PR branch locally today against a config that included this:

```yaml
            contentTests:
              - responseBodyTests:
                  - key: children
                    minLength: 2
                  - key: children[0].id
                    oneOf: ["{{{_testCreatedCategoryId}}}", "{{{_testCreatedCategoryId2}}}"]
                  - key: children[1].id
                    oneOf: 
                      - "{{_testCreatedCategoryId}}"
                      - "{{_testCreatedCategoryId2}}"
```

Here are the generated tests:

```js
// Response body should be one of the values "{{{_testCreatedCategoryId}}},{{{_testCreatedCategoryId2}}}" for "children[0].id"
if (_reschildren0Id !== undefined) {
pm.test("[PUT]::/categories/:id - Content check if value for 'children[0].id' is matching one of: '{{{_testCreatedCategoryId}}},{{{_testCreatedCategoryId2}}}'", function() {
  pm.expect(jsonData.children[0].id).to.be.oneOf(["pm.collectionVariables.get("{_testCreatedCategoryId}")","pm.collectionVariables.get("{_testCreatedCategoryId2}")"]);
})};

// Response body should be one of the values "{{_testCreatedCategoryId}},{{_testCreatedCategoryId2}}" for "children[1].id"
if (_reschildren1Id !== undefined) {
pm.test("[PUT]::/categories/:id - Content check if value for 'children[1].id' is matching one of: '{{_testCreatedCategoryId}},{{_testCreatedCategoryId2}}'", function() {
  pm.expect(jsonData.children[1].id).to.be.oneOf(["pm.collectionVariables.get("_testCreatedCategoryId")","pm.collectionVariables.get("_testCreatedCategoryId2")"]);
})};
```

There are problems with both of these outputs, but in general the second syntax (which I believe is the one that should be supported anyway) is closer.   I had thought that this would work if you wrapped the two pm.collectionVariables.get calls in the oneOf array using backticks and braces instead of double quotes, ie:

```js
// Response body should be one of the values "{{_testCreatedCategoryId}},{{_testCreatedCategoryId2}}" for "children[1].id"
if (_reschildren1Id !== undefined) {
pm.test("[PUT]::/categories/:id - Content check if value for 'children[1].id' is matching one of: '{{_testCreatedCategoryId}},{{_testCreatedCategoryId2}}'", function() {
  pm.expect(jsonData.children[1].id).to.be.oneOf([`${pm.collectionVariables.get("_testCreatedCategoryId")}`,`${pm.collectionVariables.get("_testCreatedCategoryId2")}`]);
})};
```
But this didn't work either, as I got this result:

```bash
ontent check if value for 'children[1].id' is matching one of: '{{_testCreatedCategoryId}},{{_testCreatedCategoryId2}}' | AssertionError: expected 1105065 to be one of [ '1105065', '1105067' ]
```

The only way I was able to get this to work was by manually resolving the values before making the assertion:

```js
// Response body should be one of the values "{{_testCreatedCategoryId}},{{_testCreatedCategoryId2}}" for "children[1].id"
if (_resChildren1Id !== undefined) {
pm.test("[PUT]::/categories/:id - Content check if value for 'children[1].id' is matching one of: '{{_testCreatedCategoryId}},{{_testCreatedCategoryId2}}'", function() {
  let id1 = pm.collectionVariables.get("_testCreatedCategoryId")
  let id2 = pm.collectionVariables.get("_testCreatedCategoryId")
  // pm.expect(jsonData.children[1].id).to.be.oneOf([`${pm.collectionVariables.get("_testCreatedCategoryId")}`,`${pm.collectionVariables.get("_testCreatedCategoryId2")}`]);
  pm.expect(jsonData.children[1].id).to.be.oneOf([id1, id2]);
})};
```

Which might be more trouble than it's worth?   I'll reiterate that I think its completely reasonable if Portman doesn't support postman variables in the oneOf directive within responseBodyTests!

**Reply by thim81** [reply]
hi @jpjpjp 

I'm not sure if you are using the correct version, since it the "" would be removed.

This is the config that I'm using:
```yaml
version: 1
globals:
  stripResponseExamples: true
  collectionVariables:
    _testCreatedCategoryId: abc
    _testCreatedCategoryId2: 123
overwrites:
  - openApiOperationIds:
      - post-event
    overwriteRequestBody:
      - key: event.startDateTime
        overwrite: true
        value: '2002-12-01'
tests:
  contentTests:
    - openApiOperationId: post-event
      responseBodyTests:
        - key: children
          minLength: 2
#        - key: 'childrend[0].id'
#          oneOf:
#            - '{{{_testCreatedCategoryId}}}'
#            - '{{{_testCreatedCategoryId2}}}'
        - key: 'childrend[1].id'
          oneOf:
            - '{{_testCreatedCategoryId}}'
            - '{{_testCreatedCategoryId2}}'
```

I got this result (don't mind the commented out, that was to be able to run the request):

<img width="876" alt="image" src="https://github.com/user-attachments/assets/e8fb01e4-ef50-4462-874d-a11fb0d5b56f">

<img width="1357" alt="image" src="https://github.com/user-attachments/assets/1d132365-a3d9-4795-a626-ee9fa09ef796">
