### DISCUSSION TITLE
Skip DELETE operation in all the controllers

### DISCUSSION THREAD

**Discussion by PraveenSuryaNarayanaMoorthy** [apideck-libraries/portman#656] [Q&A]
Hi All ,

  I have the below operations by default when I'm running portman it run for all the controllers in the the list, how I can skip the DELETE operartion for all the controllers and execute DELETE once other operations in all the controllers are over.
  
 orderOfOperations:
    - 'POST::/v1*'
    - 'GET::/v1*'
    - 'PUT::/v1*'
    - 'PATCH::/v1*'
    - 'DELETE::/v1*'

**Comment by thim81** [comment]
hi @PraveenSuryaNarayanaMoorthy 

That is not straight forward.The easiest way would be to generate 2 postman, using the [filtering option](https://github.com/apideck-libraries/portman/tree/main/examples/cli-filtering).

**Comment by PraveenSuryaNarayanaMoorthy** [comment]
Hi @thim81 , using tags we can filters the controllers/entities but how can we filter the HTTP methods??

[tmpCollection.json](https://github.com/user-attachments/files/16932765/tmpCollection.json)

below is my **oas-format-filter file**
```yaml
methods: []
tags: []
operationIds: []

operations:
 - *::/v2/regulations*
 - *::/v1/vehicle-types*
 - *::/v2/systems*
 - *::/v2/ecus*
```

**Comment by thim81** [comment]
@PraveenSuryaNarayanaMoorthy 

That is simple:

```yaml
methods: 
 - delete
tags: []
operationIds: []

operations:
 - *::/v2/regulations*
 - *::/v1/vehicle-types*
 - *::/v2/systems*
 - *::/v2/ecus*
```

The whole list of supported options can be found [here](https://github.com/thim81/openapi-format?tab=readme-ov-file#openapi-filter-options)

This will filter out the OpenAPI operations with the delete methods
