### DISCUSSION TITLE
openApiOperation globbing question

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#666] [Q&A] [answered]
I recently had an unexpected match in for an openAPIOperation directive in my portman-config, which includes the following:

```yaml
overwrites:
  - openApiOperation: "*::/*/{id}"
    overwriteRequestPathVariables:
      - key: id
        value: '{{<tag>Id}}'
        overwrite: true
```

In my API spec I have defined a compound API path that does not include an id path parameter as follows:

```yaml
  /plaid_accounts/fetch:
    post:
      tags:
        - plaid_accounts
      summary: Trigger Fetch from Plaid
      operationId: triggerPlaidAccountFetch
      parameters:
        - name: start_date
          in: query
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          schema:
            type: string
            format: date
        - name: plaid_account_id
          in: query
          schema:
            type: integer
```

When I run portman with this config, it is generate a request with an id path parameter:
<img width="697" alt="Screenshot 2024-10-09 at 10 20 24 AM" src="https://github.com/user-attachments/assets/5fc485d9-d314-4f7a-8bc0-76aa2b648140">

I was able to correct this by updating my config as follows:

```yaml
overwrites:
  - openApiOperation: "*::/*/{id}"
    excludeForOperations:
      - "POST::/plaid_accounts/fetch"
    overwriteRequestPathVariables:
      - key: id
        value: '{{<tag>Id}}'
        overwrite: true
```

But I hadn't expected the OpenApiOperation value  "*::/*/{id}" to match a path without the "{id}" at the end.   

This is likely a case of me not understanding the pattern-matching rules, but in case this seems odd to the portman team, I've also attached a simplified spec and config
[ReproIdInPath.zip](https://github.com/user-attachments/files/17309915/ReproIdInPath.zip)
 to reproduce.
