### DISCUSSION TITLE
Improved Validation for invalid array syntax in portman config

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#678] [Ideas]
I had a few syntax errors in my Portman config file this week, which led to some errors that were a little tricky to track down.   I'm not sure if it's realistic to improve the validation, but I'd thought I'd submit this as an idea.

Here's the first example.  Note that in this configuration, I use the keyword '-overwriteRequestBody'.   This is invalid array syntax as there should be a space between the hyphen and the directive:

```yaml
version: 1.0

# Define the tests to run 
tests:
  integrationTests:
    - name: badTest1
      operations:
      - openApiOperationId: leadsAdd
        openApiResponse: '200'
        variations:
          - name: badOverwriteRequestBody
            overwrites:
              -overwriteRequestBody:
                  - key: foo
                    value: bar
            tests:
              contentTests:
                - responseBodyTests:
                    - key: foo
                      value:  bar
```

Here is the result if I run this:
```bash
npx @apideck/portman -l /tmp/crm.yml -c /tmp/bad-config1.yaml
=========================================================================================================================================================================
 Local Path:            /tmp/crm.yml
 Portman Config:        /tmp/bad-config1.yaml
 Postman Config:        postman-config.default.json
 Environment:           .env
 Inject Tests:          true
 Run Newman:            false
 Newman Iteration Data: false
 Upload to Postman:     false  
=========================================================================================================================================================================
  ⠋ Converting OpenApi to Postman Collection
  ✔ Conversion successful
/Users/xxx/node_modules/@apideck/portman/dist/application/TestSuite.js:226
            settings.map(function (overwriteSetting) {
                     ^

TypeError: settings.map is not a function
    at TestSuite.injectOverwrites (/Users/xxx/node_modules/@apideck/portman/dist/application/TestSuite.js:226:22)
...
```

It took me a while to track this problem down.  It would have been nice if the validator would have given me an error similar to this one (which is generated if I set the directive to "- overwriteRequestBody" with the proper space after the hyphen, but missing the semicolon at the end of the directive):

```bash
npx @apideck/portman -l /tmp/crm.yml -c /tmp/bad-config1.yaml
=========================================================================================================================================================================
 Local Path:            /tmp/crm.yml
 Portman Config:        /tmp/bad-config1.yaml
 Postman Config:        postman-config.default.json
 Environment:           .env
 Inject Tests:          true
 Run Newman:            false
 Newman Iteration Data: false
 Upload to Postman:     false  
=========================================================================================================================================================================
 Invalid Portman Config:                /tmp/bad-config1.yaml
[
  {
    message: "{base}.tests.integrationTests.0.operations.0.variations.0 must have required property 'tests'",
    path: '{base}.tests.integrationTests.0.operations.0.variations.0',
    context: { errorType: 'required' }
  }
]
=========================================================================================================================================================================
```

Unzip the following in /tmp to reproduce:
[invalid-array-syntax.zip](https://github.com/user-attachments/files/17967642/invalid-array-syntax.zip)
