### DISCUSSION TITLE
Can Portman autogenerate a test to see if returned Status matches what was specified in `OpenAPIResponse` directive?

### DISCUSSION THREAD

**Discussion by jpjpjp** [apideck-libraries/portman#681] [Q&A]
I know that the default generated contract tests include a `statusSuccess` test which passes if the result is 2XX.  I was actually surprised recently when I realized that one of my APIs was returning a 200, instead of a 204, as it was intended, that it wasn't caught by the autogenerated portman tests.

Is it possible to configure Postman to automatically have a test to see if the returned status matches what was specified in the `OpenAPIResponse` directive?   Here's an example that manually does this:

```yaml
  - openApiOperationId: deleteTransactionById
    openApiResponse: "204"
    variations:
      - name: deleteFirstCreatedTrans
             overwrites:
          - overwriteRequestPathVariables:
              - key: id
                value: "{{_testCreatedTransactionId}}"
        tests:
          contractTests:
            - openApiOperationId: deleteTransactionById
              statusCode:
                enabled: true
                value: 204
```

I'd like it if I could "auto-magically" set this test so that instead of setting the value to 204, it used whatever value has been specified in the OpenAPIResponse directive.   This way I can validate that all my positive and negative tests are returning the expected error code.   

Perhaps in addition to the contractTests `statusSuccess` and `statusCode`, there could be one `statusOpenAPIResponse`?

Even if this test wasn't automatically generated, if OpenAPIResponse could be a [TemplateExpression](https://github.com/apideck-libraries/portman/tree/main/examples/testsuite-assign-overwrite#template-expressions), that would make it straightforward to add the test described above globally.
