### ISSUE TITLE
Variation test generation - generate unhappy required variation

### ISSUE THREAD

**Issue by thim81** [apideck-libraries/portman#152]
If the OpenAPI has a required field defined, Portman could generate a request body which without the required field, which should result in a "unhappy result.

```yaml
type: object
required:
- name
properties:
  name:
    type: string
  age:
    type: integer
    format: int32
    minimum: 18
   
```

The generated variation, request body would look like:
```json
{ 
  "age": 15
}
```
which is without the required "name" field.
