### ISSUE TITLE
Variation test generation - generate fuzzing variation

### ISSUE THREAD

**Issue by thim81** [apideck-libraries/portman#153]
If the OpenAPI has a string field defined, Portman could generate an invalid value for the field, which should result in a "unhappy" result.

```yaml
type: object
required:
- name
properties:
  name:
    type: string
```

The generated variation, request body would look like:
```json
{ 
  "name": "&@)à)"
}
```

Since these characters are not supported or invalid input.

We could investigate how to incorporate `big-list-of-naughty-strings` https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.json
