### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Giackgamba** [apideck-libraries/portman#260]
Hi all, thanks for the great work. 

Is there any plan for creating (and maintaining) a public Docker image for the project?
There is a couple of images on docker hub, but they are already old.

**Comment by nicklloyd** [comment]
Hi @Giackgamba - as we’ve not published any docker images, you may be looking at a different project sharing a name only…

**Comment by Giackgamba** [comment]
I was referring specifically to https://hub.docker.com/r/claudioed/portman. I tested it and it's indeed this portman. 
But I guess it's from someone that just build and uploaded it once, unlinked to the upstream repo.

My use case is that I would like to build a GitHub action for running portman, and as I'm not a js/ts/node programmer, an up-to-date image would help with that.

**Comment by thim81** [comment]
@Giackgamba Would you prefer a Docker image over a small wiki page that explains the steps or ready to use github action?

The simplest what you can do is just build a Github action that runs a taks like

```yaml
- name: Run Portman OpenAPI conversion
  run: npx -y @apideck/portman -l your-openapi-file.yaml
```

https://github.com/apideck-libraries/portman#npx-usage

**Comment by Giackgamba** [comment]
Thank you @thim81, that is really helpful indeed. I still would prefer a Docker image. 

I think that an 'official' Docker image would be a great thing for this project's adoption. It may be just me, but I tend to avoid downloading libraries just to try them out, a Docker image let me test it and forget it if I don't need it or keep it without worrying about dependencies.
Especially if they have an easy interface like this repo (and especially if they are in node, cause I don't know node and I always end up with a mess of dependencies, but that's just me).

I have a slightly more complicated use case, that is out of topic for this issue but I could/would have solved it independently if a Docker image was available.

I think a Docker image is a low-hanging fruit that is easy to implement and gives a lot of value.

I'll report here my use case here, but hidden as it's probably OT for this issue, and may be solved in other ways.
<details><summary>Slighlty more complicated use case here</summary>

One other thing I'm doing "manually" (meaning in a different action step) is the reporting of the test results using one of the many actions to publish `JUnit` results. 

I have a setup like this:
```
- name: Run Portman Contract Testing
  run: docker run --net=host -v $PWD/portman:/portman claudioed/portman --cliOptionsFile /portman/portman-cli.json 
      # ^ This can be npx -y @apideck/portman --cliOptionsFile /portman/portman-cli.json 

- name: Publish Contract Tests Results
  uses: EnricoMi/publish-unit-test-result-action@v1
  if: always()
  with:
    files: portman/contract-tests-report.xml
```

with `portman/portman-cli.json`:
```
...
"newmanRunOptions": {
    "abortOnFailure": false,
    "reporters": "junit",
    "reporter": {
      "junit": {
        "export": "/portman/contract-tests-report.xml"
      }
    }
  }
```

This is wonderful, but some things need to be aligned:
 - newman export enabled
 - `abortOnFailure: false`
 - the export file needs to be the same as the publish action search for

Nothing that can't be done manually with little experience, but I think it would be even more wonderful if it was possible to encapsulate all the logic in a stand-alone GH action with some input.

I could/would have done all that independently if a Docker image was available. (maybe there is a way to do it with [javascript actions](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action), but I'm definitely not able to, atm) 
</details>
