### ISSUE TITLE
Each examples in openapi need to be used in the postman request

### ISSUE THREAD

**Issue by george4joseph** [apideck-libraries/portman#279]
Consider an openapi.json with examples

```
#Request Parameters
examples: 
        ex1:
          summary: A foo example
          value: "foo"
        ex2:
          summary: A bar 
          value: "bar"

#Request Body
examples: 
        ex1:
          summary: A foo example
          value: {"foo": "bar"}
        ex2:
          summary: A bar example
          value: {"foo": "baz"}

#Response Body
examples: 
        ex1:
          summary: A foo example
          value: {"foo": "bar"}
        ex2:
          summary: A bar example
          value: {"foo": "baz"}
```
   
  **In postman collection my first request need to use `parameters` as  `ex1` - #Request Parameters  and #Request Body as `ex1`**
  
  Next request need to be `ex2` - #Request Parameters and `ex2` - #Request Body
  
  **Samples**
  URL: `/path/include=foo`
  BODY: `{"foo": "bar"}`
  
  URL: `/path/include=bar`
  BODY: `{"foo": "baz"}`
  
  Based on the key the examples should match. 
  
  _Is this feature is available in portman or any other way to make as I mentioned?_
