### ISSUE TITLE
Problem with overwriteRequestBody

### ISSUE THREAD

**Issue by jdevosMagento** [apideck-libraries/portman#282]
Hello,

I have a problem with overwriteRequestBody.

I want to replace the data my openApi documentation gives as an example, so i use overwriteRequestBody.

But impossible to replace the elements, portman adds a new array with new line and with the new values. 

Exemple : 

My openApi documentation :
```
properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      key_1:
                        type: string
                        example: XXXXXXXX
                      key_2:
                        type: string
                        example: XXXXXXXX
                      key_3:
                        type: string
                        example: XXXXXXXX
                      key_4:
                        type: string
                        example: XXXXXXXX
                      key_5:
                        type: string
                        example: XXXXXXXX
                      key_6:
                        type: string
                        example: XXXXXXXX
```

On Portman, my overwriteRequestBody for change the previous value :
```
"overwriteRequestBody": [
        {
            "key": "data[0].key_1",
            "value": "XXXXXXXX",
            "overwrite": true
        },
        {
            "key": "data[0].key_2",
            "value": "XXXXXXXX",
            "overwrite": true
        },
        {
            "key": "data[0].key_3",
            "value": "XXXXXXXX",
            "overwrite": true
        },
        {
            "key": "data[0].key_4",
            "value": "XXXXXXXX",
            "overwrite": true
        },
        {
            "key": "data[0].key_5",
            "value": "XXXXXXXX",
            "overwrite": true
        },
        {
            "key": "data[0].key_6",
            "value": "XXXXXXXX",
            "overwrite": true
        }
    ]
```

Result on postman :
```
{
    "data": [
        {
            "key_1": "XXXXXXXX",
            "key_2": "XXXXXXXX",
            "key_3": "XXXXXXXX",
            "key_4": "XXXXXXXX",
            "key_5": "XXXXXXXX",
            "key_6": "XXXXXXXX"
        },
        {
            "key_1": "XXXXXXXX",
            "key_2": "XXXXXXXX",
            "key_3": "XXXXXXXX",
            "key_4": "XXXXXXXX",
            "key_5": "XXXXXXXX",
            "key_6": "XXXXXXXX"
        }
    ]
}
```

The 1st data element contains the data from the overwrite RequestBody, the second contains the data from the openApi documentation

I tested several solutions with overwrite / remove, data.key_1 or data[1] with removes, but I can't get the expected working. 

Thanks for your help 
Jeremy
