### ISSUE TITLE
Overwriting Postman authorization

### ISSUE THREAD

**Issue by AliKhalili** [apideck-libraries/portman#316]
Thank you for adding [securityOverwrites - Postman authorization options](https://github.com/apideck-libraries/portman/pull/272).
I want to overwrite oAtuh2 configuration but I couldn't. As I understand, Portman only allows us to overwrite the whole auth option if there isn't any auth.
For example, in my OAS I defined a security schema and applied this schema to the OAS:
```yaml
components:
  securitySchemes:
    aad-oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://xxx
          scopes:
            read: Default API scope
security:
  - aad-oauth2:
    - read
```
and the Portman configuration is:
```yaml
globals:
  securityOverwrites:
    oauth2:
      - key: "accessTokenUrl"
        value: "{{tokenUrl}}"
        type: "string"
```
But it doesn't overwrite the access token URL at the generated Postman collection. If I removed the `security` from the OAS then it works.
I checked the source code, and I found this [line ](https://github.com/apideck-libraries/portman/blob/d13471d952efdf195e3ec1e4b9892c4ba687c09c/src/application/globals/overwriteCollectionSecurityValues.ts#L70) prevents Portman to override security and only allows us to overwrite security configuration when we don't have any security in OAS.
What should I do in this case?
Thank you for your consideration in advanced.
