### ISSUE TITLE
Support bracket notation for targeted keys in responses

### ISSUE THREAD

**Issue by Kallys** [apideck-libraries/portman#333]
### An hydra response example
```json
{
    "@context": "/contexts/Product",
    "@id": "/products",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/products/efbbbf00-0000-0000-0000-000000000000",
            "@type": "Product",
            "product_id": "efbbbf00-0000-0000-0000-000000000000",
            "description": "Incredibly fantastic product",
            "name": "Fantastic product",
        }
    ],
    "hydra:totalItems": 1,
    "hydra:view": {
        "@id": "/products?offset=0&limit=50",
        "@type": "hydra:PartialCollectionView"
    }
}
```

### A variation test
```yaml
---
version: 1
tests:
  variationTests:
    - openApiOperationId: getProducts
      variations:
        - name: Non-empty collection
          overwrites:
            - overwriteRequestHeaders:
                - key: Accept
                  value: "application/ld+json"
                  overwrite: true
          tests:
            contentTests:
              - responseBodyTests:
                - key: "['hydra:member']"
                  minLength: 1
```

### Generated script
```js
// Set response object as internal variable
let jsonData = {};
try {jsonData = pm.response.json();}catch(e){}

// Response body should have property "['hydra:member']"
pm.test("[GET]::/products - Content check if property '['hydra:member']' exists", function() {
   pm.expect((typeof jsonData.['hydra:member'] !== "undefined")).to.be.true;
// ---------------------------^ SYNTAX ERROR
});

// Response body should have a minimum length of "1" for "['hydra:member']"
if (jsonData?.['hydra:member']) {
pm.test("[GET]::/products - Content check if value of '['hydra:member']' has a minimum length of '1'", function() {
  pm.expect(jsonData.['hydra:member'].length).is.at.least(1);
// ------------------^ SYNTAX ERROR
})};
```
