### ISSUE TITLE
Ability To Expect Null/Empty Responses

### ISSUE THREAD

**Issue by whorst** [apideck-libraries/portman#388]
Some of the endpoints that my team maintains could return a response body that could be a string, timestamp, object, etc. Sometimes though, it could be null. That will cause the schema validation tests to fail, which is not necessarily what my team would want. Is there anyway to add a config option across the entire collection that would be along the lines of "Expect json body variables to be the {string, int, object, etc}, or null"? It would help me out a ton

Thanks! Your project keeps saving us lol

**Comment by thim81** [comment]
hi @whorst 

On the "null" check, you could leverage the JSON schema validation by adding "nullable: true" in OpenAPI.

Example of a property:

```yaml
MessageResultData:
      description: Metadata of a sent message.
      type: object
      properties:
        channel:
          description: This is the channel of the sent message.
          type: string
          nullable: true
```

This will make the JSON schema validation applied on the response body, allow "null" as a valid value.

Is this the use-case you refer to? 
Or are you looking for a ["contentTest"](https://github.com/apideck-libraries/portman#contenttests-options)?

**Comment by breiman** [comment]
I am running into the same issue. It would be great if Portman could treat any attribute as nullable if not listed as required within the OpenAPI definition.

In this example below, color should be treated as nullable within the schema validation tests:
```
Pet:
  type: object
  required:
    - petId
  properties:
    petId:
      type: string
    color:
      type: string
  example:
    petId: 1788
    color: gold
```
