### ISSUE TITLE
Enable a request params disable

### ISSUE THREAD

**Issue by clement-hvt** [apideck-libraries/portman#484]
Options exist to disable request parameter but not the other way around. Am I missing something or is this not planned?
To avoid the risk of breaking changes we could add an `enable` option.

**Comment by thim81** [comment]
hi @clement-hvt 

 Do you want to enable request parameters?

Through https://github.com/apideck-libraries/portman#portman---overwrites-properties you should be able to this via `disable: false`. They are enabled by default normally.
If you want to add request parameters, you can use `insert: true`

**Comment by clement-hvt** [comment]
@thim81,

if in my OpenAPI doc my parameter has `required` set to false, the parameter is disable in Postman for all requests who use it and that's normal. But,  if I want to activate it for a request neither:

```json
"overwriteRequestQueryParams": [
  {
    "key": "include[merchant]",
    "value": "xx",
    "disable": false
  }
]
```

or 

```json
"overwriteRequestQueryParams": [
  {
    "key": "include[merchant]",
    "value": "xx",
    "insert": true
  }
]
```

enable the parameter.
The overwrite is located in a test variation.

**Comment by thim81** [comment]
We will investigate this and fix it if it would be a bug.

Thanks for the detailed example.

**Comment by magicDGS** [comment]
I also found this issue with my configuration:

```yaml
...
variationTests:
    - openApiOperation: 'GET::/cardinfo.php'
      openApiResponse: '200'
      variations:
        - name: 'Misc parameter'
          overwrites:
            - overwriteRequestQueryParams:
              - key: misc
                value: 'yes'
                overwrite: true
                disable: false
...
```

Generates a postman collection where the parameter is:

```json
"query": [
  ...
  {
    "disabled": true,
    "description": {
      "content": "Show additional response info (Card Views, Beta Name, etc.).",
      "type": "text/plain"
    },
    "key": "misc",
    "value": "yes"
  },
  ...
]
```
