### ISSUE TITLE
Postman Schema tests for response body properties that are arrays with min and max items dont match

### ISSUE THREAD

**Issue by savage-alex** [apideck-libraries/portman#494]
Given the following property schema in a response body:
```
grantTypes:
          description: |
            List of grant types supported for this client.
            As per RFC6749, the clientCredentials grant can only be used by confidential clients.
            Clients SHOULD always only allow Authorization Code with PKCE.
          type: array
          minItems: 1
          maxItems: 2
          uniqueItems: true
          items:
            type: string
            enum:
              - authorizationCodePKCE
              - clientCredentials
            minLength: 0
            maxLength: 100
          example: [authorizationCodePKCE, clientCredentials]
```
This results in a postman schema test where the min and max items are 1

```
"grantTypes":{"description":"List of grant types supported for this client.\nAs per RFC6749, the clientCredentials grant can only be used by confidential clients.\nClients SHOULD always only allow Authorization Code with PKCE.\n","type":"array","minItems":1,"maxItems":1,"uniqueItems":true,"items":{"type":"string","enum":["authorizationCodePKCE","clientCredentials"],"minLength":0,"maxLength":100},"example":["authorizationCodePKCE","clientCredentials"]}
```

We also noted from trying random numbers setting min items to 0 and maxItems to 2
The generated postman schema check dropped maxItems all together.

Happy to provide a full OpenAPI example for testing on request

Thanks
