### ISSUE TITLE
Order by tags 

### ISSUE THREAD

**Issue by vampyar** [apideck-libraries/portman#621]
hi @thim81 can you help with it ?

I have this entities by by default when I'm running portman it run first entity in the the list, how I can did it without sorting in the openapi
![image](https://github.com/user-attachments/assets/e2ff2527-cca1-4602-ac6d-f87a2dd0317f)

because I did try use config, but it not helped me, it's sorted only methods:
```
version: 1
globals:
  # For every request generated omit the Postman examples
  # This helps keep the generated test collection leaner
  stripResponseExamples: true
  variableCasing: camelCase

  orderOfOperations:
    - "POST::/v1/regulations"
    - "GET::/v1/regulations"
    - "GET::/v1/regulations/{id}"
    - "PUT::/v1/regulations/{id}/*"
    - "PATCH::/v1/regulations/{id}*"
    - "DELETE::/v1/regulations/{id}"
    - "POST::/v1/vehicle-types"
    - "GET::/v1/vehicle-types/{id}*"
    - "PUT::/v1/vehicle-types/{id}*"
    - "PATCH::/v1/vehicle-types/{id}*"
    - "DELETE::/v1/vehicle-types/{id}"
    - "POST::/v1/systems"
    - "GET::/v1/systems/{id}"
    - "PUT::/v1/systems/{id}*"
    - "PATCH::/v1/systems/{id}*"
    - "DELETE::/v1/systems/{id}"
```

**Comment by thim81** [comment]
@vampyar Can you share the openapi file? So we can use that for our investigation to reproduce the behaviour?

**Comment by vampyar** [comment]
Open API
[api-json.json](https://github.com/user-attachments/files/16490888/api-json.json)

# My portman config

**oas-format-filter.yml**
```
---
methods:
tags:
operationIds:
####################################################################
# With this filters run only /v1/systems endpoints
# if you need only one specific endpoints uncomment all lines below
####################################################################
operations:
#  - "*::/v1/vehicle-types*"
#  - "*::/v2/regulations*"
#  - "*::/v1/regulations*"
#  - "*::/v1/systems*"
  - "*::/v2/vehicle-types*"
  - "*::/v2/systems*"
  - "*::/v1/releases*"
  - "*::/v2/releases*"
  - "*::/v1/ecus*"
  - "*::/v2/ecus*"
  - "*::/v1/status*"
  - "*::/v2/status*"
  ### END ####
  - "*::/v1/packages*"
  - "*::/v2/packages*"
  - "*::/v1/vehicles*"
  - "*::/v2/vehicles*"
  - "*::/v1/uploader/*"
  - "*::/v2/uploader/*"
  - "*::/v1/versions/list*"
  - "*::/v2/versions/list*"
  - "*::/v1/associations/manage*"
  - "*::/v2/associations/manage*"
  - "*::/v1/packageDistribution*"
  - "*::/v2/packageDistribution*"
  - "*::/v1/updateVehicleInfo*"
  - "*::/v2/updateVehicleInfo*"
flags: []
flagValues: []
```
**portman-cli-options.yml**
```
url: http://localhost:3000/api-json
baseUrl: http://localhost:3000
output: "./tests/portman/sums.postman.json"
collectionName: "SUMS NewMan / Portman"
portmanConfigFile: "./tests/portman/portman-config.crm.yml"
postmanConfigFile: "./tests/portman/postman-config.crm.json"
filterFile: "./tests/portman/oas-format-filter.yml"
includeTests: true
syncPostman: false # FIXME Temporary commented
runNewman: true
newmanRunOptions:
  reporters:
    - cli
    - junit
  reporter:
    junit:
      export: "junit-postman.xml"
  reporter-junit-export: "junit-postman.xml"
```
**portman-config.crm.yml**
```
version: 1
globals:
  # For every request generated omit the Postman examples
  # This helps keep the generated test collection leaner
  stripResponseExamples: true
  variableCasing: camelCase
  keyValueReplacements:
    # it's param tack automatic from env by prefix 'PORTMAN_' => PORTMAN_ADDITIONAL_TOKEN_USER
    additionaltokenuser: "{{additionalTokenUser}}"

  orderOfOperations:
    - "*::/v1/regulations"
    - "*::/v1/vehicle-types"
    - "*::/v1/system"

tests:
  contractTests:
    - openApiOperation: "*::*"
      # Check that the API returned a 2XX response
      statusSuccess:
        enabled: true
      # FIXME
#      responseTime:
#        enabled: true
#        maxMs: 300
      # Check if the response contains a Content-Type header with application/json
      contentType:
        enabled: true
      # Check if the response contaisn a JSON response body
      jsonBody:
        enabled: true
#  contentTests:
#    $ref: './tests/portman/definitions/overwrites-vehicle-types.yml#/contentTests'

assignVariables:
  - openApiOperation: "POST::*"
    collectionVariables:
      - responseBodyProp: data._id
        name: "<operationId>Id"
      - responseBodyProp: data.name
        name: "<operationId>Name"
  - openApiOperation: "PUT::*"
    collectionVariables:
      - responseBodyProp: data._id
        name: "<operationId>IdUpdated"
      - responseBodyProp: data.name
        name: "<operationId>NameUpdated"

#overwrites:
#  $ref: './tests/portman/definitions/overwrites.yml#/overwrites'
```
