### ISSUE TITLE
overwriteRequestSecurity runtime error

### ISSUE THREAD

**Issue by thim81** [apideck-libraries/portman#622]
### Discussed in https://github.com/apideck-libraries/portman/discussions/620

<div type='discussions-op-text'>

<sup>Originally posted by **jpjpjp** August  1, 2024</sup>
Hello,

  Since updating to 1.28.0 I'm getting a runtime error when I run portman:

/Users/.../node_modules/@apideck/portman/dist/application/overwrites/overwriteRequestSecurity.js:31
    var authType = authConfig.type;
                              ^
TypeError: Cannot read properties of undefined (reading 'type')

  I think I've isolated it to this test which attempts to set an invalid bearer token
  
```yaml
  operations: 
    - openApiOperationId: getMe
      openApiResponse: '401'
      variations:
        - name: unauthorized
          overwrites:
            - overwriteRequestSecurity:
                bearer:
                  token: '123'
          tests:
            $ref: ../contracts/variation-contract-tests.yaml 
            contentTests:
              - responseBodyTests:
                  - key: message
                    value: Unauthorized
                  - key: errors
                    minLength: 1
                  - key: errors[0].errMsg
                    value: Access token does not exist.
```

What's strange is that even after reverting back to portman 1.27.0 I'm still getting the same error.  I'm fairly certain this test was working before but I get this runtime error now if I include it.   Curious if anyone has any suggestions on what I can do to fix this.

  </div>
