### ISSUE TITLE
OAS parsing error for references

### ISSUE THREAD

**Issue by FreyAtGit** [apideck-libraries/portman#661]
Hi,

we get an OAS parsing error when you have references like this:
```
application/json:
   schema:
      $ref: >-
         #/components/schemas/ABC
```

it can be fixed by this:
```
application/json:
    schema:
       $ref:  '#/components/schemas/ABC'
```
