### ISSUE TITLE
Unable run my same endpoint in different query and body value 

### ISSUE THREAD

**Issue by UnlimitedGa** [apideck-libraries/portman#665]
HI team i have one problem with my script same endpoint with different query and body values i can share my script logic here cloud you please given me you support to resolve this issue thanks

```
  - openApiOperationId: "PATCH::/v1/vehicle-types/{id}/add-entity"
    overwriteRequestPathVariables:
      - key: id
        value: "{{{vehicleTypeControllerGetVehicleTypeDetailsVRequestId}}}"
    overwriteRequestQueryParams:
      - key: entity
        value: ecu
    overwriteRequestBody:
      - key: "ecus"
        value: [{"ecuId": "{{ecuControllerCreateEcuRecordId}}", "regulations": [], "systemId": "{{vehicleSystemControllerCreateVehicleSystemId}}"}]
  
   - openApiOperationId: "PATCH::/v1/vehicle-types/{id}/add-entity"
    overwriteRequestPathVariables:
      - key: id
        value: "{{vehicleTypeControllerCreateVehicleTypeId}}"
    overwriteRequestQueryParams:
      - key: entity
        value: system
    overwriteRequestBody:
      - key: "systems"
        value: [{ "regulationId": "{{regulationControllerCreateRegulationId}}", "systemId": "{{vehicleSystemControllerCreateVehicleSystemId}}"}]
```

 That patch method should call twice but only last operation performing first one not executed and can't see the logs
