### ISSUE TITLE
add operationPostResponseScript for adding post response script to postman collection

### ISSUE THREAD

**Issue by shahinshirvani** [apideck-libraries/portman#684]
Hi,

I can not add a post-response script to the postman via portman config
we have same thing for pre-request script.

kindly please add this option to the portman

**Comment by thim81** [comment]
hi @shahinshirvani 

You do that by using "[extendTests](https://github.com/apideck-libraries/portman?tab=readme-ov-file#portman---extendtests-properties)" (in the past Postman had "Tests" tab, while recently they reworked this to "Scripts" > "Pre-request" / "Post-Response"), which also allows you to use script files.

**Comment by thim81** [comment]
@jpjpjp if you can share any best-practices here, since you are using "extendTests" extensively.

**Comment by jpjpjp** [comment]
Hi @thim81  and @shahinshirvani.

I typically used extendTests in the context of integration tests.   Here's an example where the first test calls a GET endpoint and then sets a bunch of environment variables, with details about the existing data that can be used by subsequent tests:

```yaml
version: 1.0
tests:
  integrationTests:
    operations:
  - openApiOperationId: getAllCategories
    openApiResponse: '200'
    variations:
      - name: getExistingCategoryInfo
        tests:
          extendTests:
            # This test gets the current state of the existing categories and
            # creates some variables for use in subsequent tests:
            # _existingCategoryName - name of an existing category
            # _numNestedCategories - total number of categories objects in nested response
            - tests:
                - file:./specs/v2/tests/scripts/categories/post-getExistingCategoriesInfo.js
                - file:./specs/v2/tests/scripts/categories/post-validateInOrderOrAlphabetical.js
```

As you can see I typically specify the extendTests information in the context of a single request.
